### PR TITLE
don't make user.name mandatory in webhdfs requests

### PR DESCRIPTION
**Pull request by varmalho**
Reviewers: @shihccha @haitetra

### CODE REVIEW

**Comment by shihccha** [comment]
lgtm. looks like you have gone through the trouble :-)

**Comment by haitetra** [comment]
Oh, so we have to modify the library? if the lib is patched, we have to pull again?

**Comment by varmalho** [comment]
@haitetra we ship the library ourselves. Maybe I did not understand your question correctly; might be easier to explain in person.

**Comment by haitetra** [comment]
@varmalho Sure let's talk in person

**Pull request merged**
